export const FORM_ACTIONS = {
  SET_FORM_STATE: 'SET_FORM_STATE',
  SET_FIELD: 'SET_FIELD',
  SET_FIRSTNAME: 'SET_FIRSTNAME',
  SET_LASTNAME: 'SET_LASTNAME',
  SET_EMAIL: 'SET_EMAIL',
  SET_PASSWORD: 'SET_PASSWORD',
  SET_COUNTRY: 'SET_COUNTRY',
  SET_STATE: 'SET_STATE',
  SET_CITY: 'SET_CITY',
  SET_ADDRESS: 'SET_ADDRESS',
  SET_IMAGE_URL: 'SET_IMAGE_URL',
  SET_ISLOADING: 'SET_ISLOADING',
  SET_FIRSTNAME_ERROR: 'SET_FIRSTNAME_ERROR',
  SET_LASTNAME_ERROR: 'SET_LASTNAME_ERROR',
  SET_EMAIL_ERROR: 'SET_EMAIL_ERROR',
  SET_PASSWORD_ERROR: 'SET_PASSWORD_ERROR',
  SET_ADDRESS_ERROR: 'SET_ADDRESS_ERROR',
  RESET_ERRORS: 'RESET_ERRORS',
  REGISTRATION_REQUEST: 'REGISTRATION_REQUEST',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  SET_REGISTERED: 'SET_REGISTERED',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGINOAUTH_REQUEST: 'LOGINOAUTH_REQUEST',
  LOGIN_FAILED: 'LOGIN_FAILED',
  LOGINOAUTH_FAILED: 'LOGINOAUTH_FAILED',
  SET_USER_DETAILS: 'SET_USER_DETAILS',
  UPDATE_REQUEST: 'UPDATE_REQUEST',
  UPDATE_FAILED: 'UPDATE_FAILED',
  SET_UPDATED: 'SET_UPDATED',
  ADD_PRODUCT_REQUEST: 'ADD_PRODUCT_REQUEST',
  UPDATE_PRODUCT_REQUEST: 'UPDATE_PRODUCT_REQUEST',
  SEARCH_REQUEST: 'SEARCH_REQUEST',
  SEARCH_FAILED: 'SEARCH_FAILED',
  SET_SEARCHPRODUCT: 'SET_SEARCHPRODUCT',
  RESET_STATE: 'RESET_STATE',
  SET_IMAGEURL_ERROR: 'SET_IMAGEURL_ERROR',
  SET_FORM_STATE1: 'SET_FORM_STATE1'
};

export const CART_REDUCER = {
  GET_CART_ITEMS: 'GET_CART_ITEMS',
  SET_CART_ITEMS: 'SET_CART_ITEMS',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  DELETE_CART_ITEM_API: 'DELETE_CART_ITEM_API',
  UPDATE_ITEM_QUANTITY: 'UPDATE_ITEM_QUANTITY',
  ADD_CART_ITEM: 'ADD_CART_ITEM'
};

export const PRODUCT_LIST_REDUCER = {
  GET_PRODUCT_LIST: 'GET_PRODUCT_LIST',
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST',
  UPDATE_PRODUCT_LIST: 'UPDATE_PRODUCT_LIST',
  GET_PRODUCT: 'GET_PRODUCT',
  DELETE_FILTERS: 'DELETE_FILTERS',
  SET_FILTERS: 'SET_FILTERS',
  APPLY_FILTERS: 'APPLY_FILTERS',
  SET_ALERT: 'SET_ALERT',
  SET_MIN_MAX: 'SET_MIN_MAX',
  RESET_PRODUCT_LIST: 'RESET_PRODUCT_LIST',
  DELETE_PRODUCT: 'DELETE_PRODUCT',
  ADD_PRODUCT: 'ADD_PRODUCT',
  UPDATE_PRODUCT: 'UPDATE_PRODUCT',
  SET_UPDATE_PRODUCT_ID: 'SET_UPDATE_PRODUCT_ID',
  SET_FILTERED_PRODUCTS: 'SET_FILTERED_PRODUCTS',
  APPLY_PRICE_FILTER: 'APPLY_PRICE_FILTER',
  RESET_FILTER: 'RESET_FILTER'
  // SET_COPY_PRODUCT_LIST: 'SET_COPY_PRODUCT_LIST',
  // SET_SUB_PRODUCT_LIST: 'SET_SUB_PRODUCT_LIST'
};

export const FOOTER_ELEMENT_LIST_REDUCER = {
  GET_FOOTER_ELEMENT_LIST: 'GET_FOOTER_ELEMENT_LIST',
  SET_FOOTER_ELEMENT_LIST: 'SET_FOOTER_ELEMENT_LIST'
};

export const USERPROFILE_REDUCER = {
  GET_USER_PROFILE: 'GET_USER_PROFILE',
  SET_USER_PROFILE: 'SET_USER_PROFILE'
};

export const ADMIN_PRODUCT_REDUCER = {
  SET_PRODUCT_LIST: 'SET_PRODUCT_LIST'
};

export const USER_LIST_REDUCER = {
  SET_USER_LIST: 'SET_USER_LIST',
  GET_USER_LIST: 'GET_USER_LIST',
  DELETE_USER: 'DELETE_USER',
  DISABLE_USER: 'DISABLE_USER',
  ENABLE_USER: 'ENABLE_USER'
};
export const PRODUCT_ACTIONS = {
  SET_PRODUCTTITLE_ERROR: 'SET_PRODUCTTITLE_ERROR',
  SET_DESCRIPTION_ERROR: 'SET_DESCRIPTION_ERROR',
  SET_PRODUCTPRICE_ERROR: 'SET_PRODUCTPRICE_ERROR',
  SET_DISCOUNT_ERROR: 'SET_DISCOUNT_ERROR',
  SET_TAX_ERROR: 'SET_TAX_ERROR',
  SET_STOCK_ERROR: 'SET_STOCK_ERROR',
  SET_BRAND_ERROR: 'SET_BRAND_ERROR',
  SET_COLOR_ERROR: 'SET_COLOR_ERROR',
  SET_SIZE_ERROR: 'SET_SIZE_ERROR',
  SET_IMAGEURL_ERROR: 'SET_IMAGEURL_ERROR',
  SET_PRODUCT_ADDED: 'SET_PRODUCT_ADDED',
  SET_PRODUCT_UPDATED: 'SET_PRODUCT_UPDATED'
};

export const ALERT_ACTIONS = {
  ALERT_MESSAGE: 'ALERT_MESSAGE',
  ALERT_LOGIN: 'ALERT_LOGIN',
  ALERT_USER_PROFILE: 'ALERT_USER_PROFILE',
  ALERT_REGISTRATION: 'ALERT_REGISTRATION'
};
