export const CART_REDUCER = {
  GET_CARTITEMS: 'GET_CARTITEMS',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  UPDATE_ITEM_QUANTITY: 'UPDATE_ITEM_QUANTITY',
  ADD_CART_ITEM: 'ADD_CART_ITEM'
};

export const PRODUCT_LIST_REDUCER = {
  GET_PRODUCT_LIST: 'GET_PRODUCT_LIST'
};
