export const FORM_ACTIONS = {
  SET_FIELD: 'SET_FIELD',
  SET_FIRSTNAME: 'SET_FIRSTNAME',
  SET_LASTNAME: 'SET_LASTNAME',
  SET_EMAIL: 'SET_EMAIL',
  SET_PASSWORD: 'SET_PASSWORD',
  SET_COUNTRY: 'SET_COUNTRY',
  SET_STATE: 'SET_STATE',
  SET_CITY: 'SET_CITY',
  SET_ADDRESS: 'SET_ADDRESS',
  SET_ISLOADING: 'SET_ISLOADING',
  SET_FIRSTNAME_ERROR: 'SET_FIRSTNAME_ERROR',
  SET_LASTNAME_ERROR: 'SET_LASTNAME_ERROR',
  SET_EMAIL_ERROR: 'SET_EMAIL_ERROR',
  SET_PASSWORD_ERROR: 'SET_PASSWORD_ERROR',
  SET_ADDRESS_ERROR: 'SET_ADDRESS_ERROR',
  RESET_ERRORS: 'RESET_ERRORS',
  REGISTRATION_REQUEST: 'REGISTRATION_REQUEST',
  REGISTRATION_FAILED: 'REGISTRATION_FAILED',
  SET_REGISTERED: 'SET_REGISTERED',
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILED: 'LOGIN_FAILED',
  SET_USER_DETAILS: 'SET_USER_DETAILS'
};

export const CART_REDUCER = {
  GET_CARTITEMS: 'GET_CARTITEMS',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
  UPDATE_ITEM_QUANTITY: 'UPDATE_ITEM_QUANTITY',
  ADD_CART_ITEM: 'ADD_CART_ITEM'
};

export const PRODUCT_LIST_REDUCER = {
  GET_PRODUCT_LIST: 'GET_PRODUCT_LIST'
};
